export const cyprusRegions = ["Girne", "Lefkoşa", "Mağusa", "İskele", "Güzelyurt", "Lefke"];

export const packages = [ 
  { name: "Standart Paket", price: `60 STG / Aylık` }, 
  { name: "Premium Paket", price: `100 STG / Aylık` } 
];

export const categories = [ 
  { key: "barber", dbName: "Berber", bg: "linear-gradient(135deg,#1a1a2e,#2d1b4e)", emoji: "💈" }, 
  { key: "hair", dbName: "Kuaför", bg: "linear-gradient(135deg,#f5c5a3,#e8622a)", emoji: "✂️" }, 
  { key: "nail", dbName: "Tırnak & Güzellik", bg: "linear-gradient(135deg,#ffd6e7,#ff88b2)", emoji: "💅" }, 
  { key: "tattoo", dbName: "Dövme", bg: "linear-gradient(135deg,#1a1a1a,#444)", emoji: "🖋️" }, 
  { key: "spa", dbName: "Spa & Masaj", bg: "linear-gradient(135deg,#d4f5e9,#00c48c)", emoji: "💆" }, 
  { key: "skincare", dbName: "Cilt Bakımı", bg: "linear-gradient(135deg,#e8f4fd,#3498db)", emoji: "🧴" }, 
  { key: "makeup", dbName: "Makyaj", bg: "linear-gradient(135deg,#fff0e6,#e8622a)", emoji: "💄" }, 
  { key: "club", dbName: "Bar & Club", bg: "linear-gradient(135deg,#1a0a0a,#3d1515)", emoji: "🍸" } 
];

export const featNames = { profile: "Bookcy Profili", market: "Pazaryeri Listeleme", team: "Ekip Yönetimi", booking: "Online Randevu", app: "Müşteri Uygulaması", marketing: "Pazarlama Araçları", calendar: "Takvim & Planlama", crm: "Müşteri Yönetimi", boost: "Öne Çık", stats: "İstatistik & Raporlar" };

export const featDesc = { profile: "İşletmenizin dijital vitrinini saniyeler içinde oluşturun.", market: "Bookcy kullanan binlerce aktif müşteriye doğrudan ulaşın.", team: "Personelinizin çalışma saatlerini kolayca yönetin.", booking: "Müşterilerinizin 7/24 randevu almasını sağlayın.", app: "Müşterilerinize özel mobil uygulama konforu sunun.", marketing: "Doğru zamanda doğru mesajı gönderin.", calendar: "Akıllı dijital takvim ile çakışmaları önleyin.", crm: "Müşteri geçmişini güvenle saklayın.", boost: "Aramalarda üst sıralara çıkın.", stats: "Anlık ve net raporlarla kazancınızı görün." };

export const t = {
  TR: {
    nav: { places: "İşletmeler", features: "Özellikler", why: "Neden Bookcy", about: "Hakkımızda & Paketler", contact: "İletişim", addShop: "İşletme Ekle", login: "Giriş", logout: "Çıkış", panel: "Panel" },
    mega: { setup: "Kurulum", engage: "Müşterileri Etkile", manage: "İşletmeni Yönet", grow: "Büyümeye Devam Et", btn: "Tüm Özellikleri Keşfet" },
    hero: { eyebrow: "Kıbrıs'ın #1 Güzellik Platformu", title1: "Kendine", title2: "iyi bak,", title3: "hemen", title4: "randevu al.", sub: "Yakınındaki en iyi berber, kuaför, spa ve güzellik uzmanlarını bul. Tek tıkla randevu al, zamanın senin olsun.", searchPlace: "Hizmet veya mekan ara...", searchLoc: "Nerede?", btn: "ARA", pop: "Popüler:", stat1: "Aktif İşletme", stat2: "Mutlu Müşteri", stat3: "Tamamlanan İşlem", stat4: "Memnuniyet" },
    cats: { title: "Kategoriler", sub: "Bugün ne yaptırmak istersiniz?", seeAll: "Tümünü Gör →" },
    featured: { title: "Öne Çıkanlar", sub: "Kıbrıs'ta Bu Hafta 🔥" },
    how: { title: "Nasıl Çalışır?", sub: "4 Basit Adımda Randevun Hazır", s1: "Keşfet", d1: "Yakındaki mekanları incele ve filtrele.", s2: "Tarih Seç", d2: "Sana en uygun zamanı tek tıkla seç.", s3: "Onayla", d3: "Saniyeler içinde rezervasyonun onaylanır.", s4: "Keyif Çıkar", d4: "Git, hizmetini al ve puan ver." },
    why: { tag: "Farkı Keşfedin", title1: "Neden", title2: "Bookcy", title3: "Kullanıyorlar?", sub: "Kişisel bakım yolculuğunuzun en güvenilir ortağıyız.", c1: "Öncü Platform", d1: "Kıbrıs’ta ilk ve öncü randevu platformlarından biri olarak, sektöre yön veriyoruz.", c2: "Entegre Sistem", d2: "Farklı sektörleri tek çatı altında toplayarak kapsamlı deneyim sunuyoruz.", c3: "Gerçek Müşteri", d3: "İşletmelere gerçek müşteri kazandıran aktif bir trafik sağlıyoruz.", c4: "Üst Düzey Arayüz", d4: "Sade, hızlı ve kullanıcı dostu modern bir arayüz sunuyoruz.", c5: "Maksimum Kazanç", d5: "İşletmeler için adil, şeffaf ve komisyonsuz modelimiz ile gelirinizi katlamanızı sağlıyoruz.", c6: "Gelişmiş Otomasyon", d6: "Yüksek performanslı altyapımızla yakında eklenecek SMS ve gelişmiş bildirim sistemleri.", btn: "Hemen Aramıza Katıl" },
    aboutPage: { tag: "Sektörün Dijital Devrimi", title1: "İşletmeni Dijitale Taşı,", title2: "Kazancını Katla", sub: "Kıbrıs’taki en iyi işletmeler randevularını Bookcy ile yönetiyor.", wTag: "Biz Kimiz?", w1: "Bookcy, Kıbrıs’ta kurulan ilk ve tek kapsamlı online randevu platformu olarak, işletmelerin dijital dönüşümünü hızlandırmak için geliştirilmiştir.", w2: "Güzellikten bakıma, spadan yaşam tarzı hizmetlerine kadar birçok sektörü tek çatı altında buluşturarak, hem işletmelere hem müşterilere yeni nesil bir deneyim sunuyoruz.", w3: "Biz sadece bir randevu sistemi değiliz", w4: "işletmelerin büyümesini sağlayan dijital altyapıyız.", pTag: "Size Uygun Planı Seçin", pTitle: "İşletme Paketleri", std: "Standart Paket", mo: "/ Aylık", pr: "Premium Paket", pop: "En Çok Tercih Edilen", btn1: "Hemen Başla", btn2: "Premium'a Geç" },
    contactPage: { title: "BİZE ULAŞIN", sub: "Sorularınız, destek talepleriniz veya sponsorluk görüşmeleri için bize her zaman ulaşabilirsiniz.", wp1: "Anında destek ve işletme başvuruları için bize yazın.", wp2: "MESAJ GÖNDER", ig1: "En yeni mekanları keşfedin ve bizi takip edin.", ig2: "TAKİP ET", mail1: "Kurumsal görüşmeler ve reklam teklifleri için.", mail2: "MAİL AT" },
    footer: { desc: "Bookcy, Kıbrıs'ın pazar lideri ve en kapsamlı yeni nesil randevu platformudur.", col1: "Platform", col2: "Bölgeler", col3: "Yasal & Sözleşmeler", right1: "Tüm hakları saklıdır." },
    legal: { upd: "Son Güncelleme: 10 Nisan 2024" },
    modal: { regTitle: "İŞLETME KAYIT", regSub: "Sadece İşletme Sahipleri İçindir", shopName: "İşletme Adı", address: "Tam Adres", map: "Google Maps Linki", phone: "İşletme Telefonu", insta: "Instagram Linki", mail: "İletişim E-Posta", adminMail: "Admin E-Posta (Giriş için)", desc: "Hakkımızda", logo: "Logo Yükle", user: "Kullanıcı Adı", pass: "Şifre", btnReg: "BAŞVURUYU TAMAMLA", loading: "YÜKLENİYOR...", success: "BAŞVURUNUZ ALINDI!", bank: "Banka Bilgileri / Bank Details:", bankDesc: "Bizi tercih ettiğiniz için teşekkür ederiz. İşletme profilinizin onaylanıp yayına alınabilmesi için lütfen ödeme dekontunuzu WhatsApp destek hattımız üzerinden bize iletiniz.", btnBank: "DEKONTU İLET", logTitle: "GİRİŞ YAP", logSub: "İŞ ORTAĞI PANELİ", own: "YÖNETİCİ", stf: "PERSONEL", wait: "BEKLEYİN...", btnLog: "PANELE GİT" },
    cookie: { title: "Çerez Politikası ve Gizlilik Sözleşmesi", desc1: "Size daha iyi bir deneyim sunabilmek için çerezleri kullanıyoruz. Sitemizi kullanmaya devam ederek", l1: "Çerez Politikamızı", desc2: "ve", l2: "Gizlilik Sözleşmemizi", desc3: "kabul etmiş olursunuz.", btn1: "İncele", btn2: "Kabul Ediyorum" },
    featNames: { profile: "Bookcy Profili", market: "Pazaryeri Listeleme", team: "Ekip Yönetimi", booking: "Online Randevu", app: "Müşteri Uygulaması", marketing: "Pazarlama Araçları", calendar: "Takvim & Planlama", crm: "Müşteri Yönetimi", boost: "Öne Çık", stats: "İstatistik & Raporlar" },
    featDesc: { profile: "İşletmenizin dijital vitrinini saniyeler içinde oluşturun.", market: "Bookcy kullanan binlerce aktif müşteriye doğrudan ulaşın.", team: "Personelinizin çalışma saatlerini kolayca yönetin.", booking: "Müşterilerinizin 7/24 randevu almasını sağlayın.", app: "Müşterilerinize özel mobil uygulama konforu sunun.", marketing: "Doğru zamanda doğru mesajı gönderin.", calendar: "Akıllı dijital takvim ile çakışmaları önleyin.", crm: "Müşteri geçmişini güvenle saklayın.", boost: "Aramalarda üst sıralara çıkın.", stats: "Anlık ve net raporlarla kazancınızı görün." }
  },
  EN: {
    nav: { places: "Businesses", features: "Features", why: "Why Bookcy", about: "About & Packages", contact: "Contact", addShop: "Add Business", login: "Login", logout: "Logout", panel: "Dashboard" },
    mega: { setup: "Setup", engage: "Engage Clients", manage: "Manage Business", grow: "Keep Growing", btn: "Explore All Features" },
    hero: { eyebrow: "Cyprus's #1 Beauty Platform", title1: "Take care", title2: "of yourself,", title3: "book", title4: "instantly.", sub: "Find the best barbers, salons, spas and beauty experts nearby.", searchPlace: "Search services or places...", searchLoc: "Where?", btn: "SEARCH", pop: "Popular:", stat1: "Active Businesses", stat2: "Happy Clients", stat3: "Completed Bookings", stat4: "Satisfaction" },
    cats: { title: "Categories", sub: "What are you looking for today?", seeAll: "See All →" },
    featured: { title: "Featured", sub: "Trending This Week 🔥" },
    how: { title: "How it works?", sub: "Ready in 4 Simple Steps", s1: "Discover", d1: "Find and filter nearby places.", s2: "Select Date", d2: "Pick the best time with one click.", s3: "Confirm", d3: "Booking confirmed in seconds.", s4: "Enjoy", d4: "Get your service and leave a rating." },
    why: { tag: "Discover the Difference", title1: "Why", title2: "Bookcy?", title3: "", sub: "Your most trusted partner in personal care.", c1: "Pioneer Platform", d1: "As the first and leading booking platform in Cyprus, we guide the industry.", c2: "Integrated System", d2: "We offer a comprehensive experience by bringing different sectors under one roof.", c3: "Real Customers", d3: "We provide active traffic that brings real customers to businesses.", c4: "High-End Interface", d4: "We offer a simple, fast, and user-friendly modern interface.", c5: "Maximum Profit", d5: "We help you multiply your income with our fair, transparent, zero-commission model.", c6: "Advanced Automation", d6: "Upcoming SMS and advanced notification systems with our high-performance infrastructure.", btn: "Join Us Now" },
    aboutPage: { tag: "The Industry's Digital Revolution", title1: "Digitize Your Business,", title2: "Multiply Your Income", sub: "The best businesses in Cyprus manage their bookings with Bookcy.", wTag: "Who Are We?", w1: "Bookcy, as the first and only comprehensive online booking platform founded in Cyprus, was developed to accelerate the digital transformation of businesses.", w2: "By bringing many sectors under one roof, we offer a next-generation experience.", w3: "We are not just a booking system", w4: "we are the digital infrastructure that enables businesses to grow.", pTag: "Choose Your Plan", pTitle: "Business Packages", std: "Standard Package", mo: "/ Month", pr: "Premium Package", pop: "Most Popular", btn1: "Get Started", btn2: "Upgrade to Premium" },
    contactPage: { title: "CONTACT US", sub: "You can always reach out to us for questions, support requests, or sponsorship inquiries.", wp1: "Write to us for instant support and business applications.", wp2: "SEND MESSAGE", ig1: "Discover the newest places and follow us.", ig2: "FOLLOW", mail1: "For corporate inquiries and advertising offers.", mail2: "SEND EMAIL" },
    footer: { desc: "Bookcy is Cyprus's market-leading and most comprehensive next-generation booking platform.", col1: "Platform", col2: "Regions", col3: "Legal & Terms", right1: "All rights reserved." },
    legal: { upd: "Last Update: April 10, 2024" },
    modal: { regTitle: "BUSINESS REGISTRATION", regSub: "For Business Owners Only", shopName: "Business Name", address: "Full Address", map: "Google Maps Link", phone: "Business Phone", insta: "Instagram Link", mail: "Contact Email", adminMail: "Admin Email (For Login)", desc: "About Us", logo: "Upload Logo", user: "Username", pass: "Password", btnReg: "COMPLETE APPLICATION", loading: "UPLOADING...", success: "APPLICATION RECEIVED!", bank: "Bank Details:", bankDesc: "Thank you for choosing us. Please send your payment receipt via our WhatsApp support line.", btnBank: "SEND RECEIPT", logTitle: "LOGIN", logSub: "PARTNER DASHBOARD", own: "OWNER", stf: "STAFF", wait: "PLEASE WAIT...", btnLog: "GO TO DASHBOARD" },
    cookie: { title: "Cookie Policy & Privacy Agreement", desc1: "We use cookies to provide you with a better experience. By continuing to use our site, you agree to our", l1: "Cookie Policy", desc2: "and", l2: "Privacy Policy", desc3: ".", btn1: "Review", btn2: "I Accept" },
    featNames: { profile: "Bookcy Profile", market: "Marketplace Listing", team: "Team Management", booking: "Online Booking", app: "Customer App", marketing: "Marketing Tools", calendar: "Calendar & Planning", crm: "Client Management", boost: "Boost", stats: "Stats & Reports" },
    featDesc: { profile: "Create your digital storefront in seconds.", market: "Reach thousands of active customers directly.", team: "Easily manage your staff's working hours.", booking: "Allow your clients to book 24/7.", app: "Offer exclusive mobile app comfort to your clients.", marketing: "Send the right message at the right time.", calendar: "Prevent conflicts with a smart digital calendar.", crm: "Safely store your client history.", boost: "Rank higher in search results.", stats: "See your earnings with instant and clear reports." }
  },
  RU: {
    nav: { places: "Заведения", features: "Функции", why: "Почему Bookcy", about: "О нас и пакеты", contact: "Контакты", addShop: "Добавить бизнес", login: "Вход", logout: "Выйти", panel: "Панель" },
    mega: { setup: "Настройка", engage: "Привлечение клиентов", manage: "Управление", grow: "Развитие", btn: "Все функции" },
    hero: { eyebrow: "Платформа красоты #1 на Кипре", title1: "Позаботьтесь", title2: "о себе,", title3: "забронируйте", title4: "сейчас.", sub: "Найдите лучших мастеров поблизости. Бронируйте в один клик, ваше время принадлежит вам.", searchPlace: "Поиск услуг или мест...", searchLoc: "Где?", btn: "ПОИСК", pop: "Популярные:", stat1: "Активные заведения", stat2: "Счастливые клиенты", stat3: "Завершенные брони", stat4: "Удовлетворенность" },
    cats: { title: "Категории", sub: "Что вы ищете сегодня?", seeAll: "Показать все →" },
    featured: { title: "Рекомендуемые", sub: "В тренде на этой неделе 🔥" },
    how: { title: "Как это работает?", sub: "Готово за 4 простых шага", s1: "Найти", d1: "Ищите заведения поблизости.", s2: "Выбрать", d2: "Выберите лучшее время.", s3: "Подтвердить", d3: "Мгновенное подтверждение.", s4: "Наслаждаться", d4: "Получите услугу и оцените." },
    why: { tag: "Почувствуйте разницу", title1: "Почему", title2: "выбирают", title3: "Bookcy?", sub: "Ваш надежный партнер в сфере ухода за собой.", c1: "Платформа-лидер", d1: "Первая и ведущая платформа бронирования на Кипре.", c2: "Интегрированная система", d2: "Различные сектора под одной крышей.", c3: "Реальные клиенты", d3: "Активный трафик реальных клиентов.", c4: "Современный интерфейс", d4: "Простой и удобный дизайн.", c5: "Максимум дохода", d5: "Справедливая модель без комиссий.", c6: "Продвинутая автоматизация", d6: "Скоро: SMS и смарт-уведомления.", btn: "Присоединяйтесь сейчас" },
    shops: { back: "НАЗАД", title: "Результаты поиска", found: "Мест найдено", search: "Поиск...", allReg: "Все регионы", allCat: "Все категории", select: "ВЫБРАТЬ", empty: "По вашим критериям ничего не найдено." },
    profile: { events: "События", services: "Услуги", gallery: "Галерея", about: "О нас", soldOut: "РАСПРОДАНО", select: "ВЫБРАТЬ", emptySrv: "Услуги еще не добавлены.", emptyGal: "Галерея пуста.", emptyDesc: "Описание еще не добавлено." },
    booking: { title: "Детали бронирования", back: "Назад", startEvent: "Выберите событие для начала.", startSrv: "Выберите услугу для продолжения.", srv: "Услуга", staff: "Специалист", time: "Время", total: "Итого", selectStaff: "Выберите специалиста", any: "Любой", closed: "ЗАКРЫТО В ЭТУ ДАТУ", name: "Имя", surname: "Фамилия", phone: "Телефон", email: "Email", confirm: "ПОДТВЕРДИТЬ БРОНЬ" },
    success: { title: "БРОНЬ ПОДТВЕРЖДЕНА", desc: "Ваши данные отправлены. Пожалуйста, будьте на месте вовремя.", rateTitle: "Оцените нас", q1: "Как вам?", q2: "Легко ли использовать?", q3: "Вы довольны?", q4: "Было ли быстро?", btn: "Отправить и завершить", thanks: "Спасибо!", saved: "Ваша оценка успешно сохранена.", home: "НА ГЛАВНУЮ" },
    aboutPage: { tag: "Цифровая революция отрасли", title1: "Оцифруйте бизнес,", title2: "Умножьте доход", sub: "Лучшие заведения Кипра управляют бронированиями с Bookcy.", wTag: "Кто мы?", w1: "Bookcy — первая комплексная платформа онлайн-бронирования на Кипре, созданная для цифровой трансформации бизнеса.", w2: "Объединяя множество секторов, мы предлагаем новый опыт как для бизнеса, так и для клиентов.", w3: "Мы не просто система бронирования", w4: "мы — цифровая инфраструктура для роста вашего бизнеса.", pTag: "Выберите свой план", pTitle: "Пакеты для бизнеса", std: "Стандартный Пакет", mo: "/ в месяц", pr: "Премиум Пакет", pop: "Самый популярный", btn1: "Начать", btn2: "Перейти на Премиум" },
    contactPage: { title: "СВЯЖИТЕСЬ С НАМИ", sub: "Вы всегда можете связаться с нами для вопросов, поддержки или сотрудничества.", wp1: "Напишите нам для мгновенной поддержки.", wp2: "ОТПРАВИТЬ СООБЩЕНИЕ", ig1: "Открывайте новые места и подписывайтесь на нас.", ig2: "ПОДПИСАТЬСЯ", mail1: "Для корпоративных запросов и рекламы.", mail2: "ОТПРАВИТЬ EMAIL" },
    footer: { desc: "Bookcy — ведущая платформа бронирования нового поколения на Кипре.", col1: "Платформа", col2: "Регионы", col3: "Документы", right1: "Все права защищены." },
    legal: { upd: "Последнее обновление: 10 апреля 2024 г." },
    modal: { regTitle: "РЕГИСТРАЦИЯ БИЗНЕСА", regSub: "Только для владельцев", shopName: "Название бизнеса", address: "Полный адрес", map: "Ссылка на Google Maps", phone: "Телефон", insta: "Ссылка на Instagram", mail: "Email для связи", adminMail: "Email администратора", desc: "О нас", logo: "Загрузить логотип", user: "Имя пользователя", pass: "Пароль", btnReg: "ЗАВЕРШИТЬ РЕГИСТРАЦИЮ", loading: "ЗАГРУЗКА...", success: "ЗАЯВКА ПОЛУЧЕНА!", bank: "Банковские реквизиты:", bankDesc: "Спасибо, что выбрали нас. Пожалуйста, отправьте квитанцию об оплате в WhatsApp, чтобы мы могли подтвердить ваш профиль.", btnBank: "ОТПРАВИТЬ КВИТАНЦИЮ", logTitle: "ВХОД", logSub: "ПАНЕЛЬ ПАРТНЕРА", own: "МЕНЕДЖЕР", stf: "ПЕРСОНАЛ", wait: "ПОДОЖДИТЕ...", btnLog: "ВОЙТИ" },
    cookie: { title: "Политика использования файлов cookie", desc1: "Мы используем файлы cookie. Продолжая использовать сайт, вы соглашаетесь с", l1: "Политикой cookie", desc2: "и", l2: "Политикой конфиденциальности", desc3: ".", btn1: "Обзор", btn2: "Я согласен" },
    featNames: { profile: "Профиль Bookcy", market: "Маркетплейс", team: "Управление командой", booking: "Онлайн-бронирование", app: "Приложение клиента", marketing: "Инструменты маркетинга", calendar: "Календарь и планирование", crm: "Управление клиентами", boost: "Продвижение", stats: "Статистика и отчеты" },
    featDesc: { profile: "Создайте витрину за секунды.", market: "Охватите тысячи активных клиентов.", team: "Управляйте графиком персонала.", booking: "Позвольте клиентам бронировать 24/7.", app: "Предложите клиентам удобное мобильное приложение.", marketing: "Отправляйте сообщения в нужное время.", calendar: "Избегайте накладок с помощью смарт-календаря.", crm: "Надежно храните историю клиентов.", boost: "Поднимитесь в результатах поиска.", stats: "Следите за доходами с помощью отчетов." }
  }
};